ALTER TABLE TOPIC_PROGRESS ADD TOPIC_NAME VARCHAR(255);

UPDATE TOPIC_PROGRESS SET TOPIC_NAME = ( SELECT t.name FROM topic t WHERE t.id = topic_id ) 
WHERE EXISTS ( SELECT t.id FROM topic t WHERE t.id = topic_id );
