-- Drop tables
--alter table HOMEWORK drop constraint HOMEWORK_FK_STUDENT;
--alter table TOPIC drop constraint TOPIC_FK_MOD;
--alter table HOMEWORK_MODULE drop constraint HOMEWORK_MODULE_FK_HW;
--alter table HOMEWORK_MODULE drop constraint HOMEWORK_MODULE_FK_MOD;

drop table HOMEWORK if exists;
drop table STUDENT if exists;
drop table TOPIC if exists;
drop table MODULE if exists;
drop table HOMEWORK_MODULE if exists;

-- Create tables

------------
-- MODULE --
------------
create table MODULE (
ID integer generated by default as identity (start with 1), 
DESC varchar(255), 
NAME varchar(255) not null, 
primary key (ID), 
unique (NAME));

------------
-- STUDENT --
------------ 
create table STUDENT (
ID integer generated by default as identity (start with 1), 
NAME varchar(255) not null, 
EMAIL varchar(255), 
primary key (ID));


------------
-- HOMEWORK --
------------ 
create table HOMEWORK (
ID integer generated by default as identity (start with 1), 
STUD_ID integer, primary key (ID));

alter table HOMEWORK add constraint HOMEWORK_FK_STUDENT foreign key (STUD_ID) references STUDENT;

------------
-- TOPIC --
------------ 
create table TOPIC (
ID integer generated by default as identity (start with 1), 
DESC varchar(255), 
NAME varchar(255) not null, 
MOD_ID integer, 
primary key (ID), 
unique (NAME));

alter table TOPIC add constraint TOPIC_FK_MOD foreign key (MOD_ID) references MODULE;

------------
-- HOMEWORK_MODULE --
------------ 
create table HOMEWORK_MODULE (
HW_ID integer not null, 
MODULE_ID integer not null);

alter table HOMEWORK_MODULE add constraint HOMEWORK_MODULE_FK_HW foreign key (HW_ID) references HOMEWORK;
alter table HOMEWORK_MODULE add constraint HOMEWORK_MODULE_FK_MOD foreign key (MODULE_ID) references MODULE;
